[parity]
  mode = "active"
  mode_timeout = 300
  mode_alarm = 3600
  auto_update = "critical"
  release_track = "stable"
  public_node = true
  no_download = false
  no_consensus = false
  chain = "kovan"                           // need to change
  base_path = "/home/openethereum"          // need to change
  db_path = "/home/openethereum/chains"     // need to change
  keys_path = "/home/openethereum/keys"     // need to change

[network]
  port = 30303
  min_peers = 100
  max_peers = 200
  discovery = true
  warp = true
  allow_ips = "all"
  nat = "extip:0.0.0.0"                     // need to change
  # Parity will maintain additional 128 peers for snapshot sync.
  snapshot_peers = 128
  # Parity will allow up to 256 pending connections.
  max_pending_peers = 512

[footprint]
  tracing = "off"
  db_compaction = "ssd"
  cache_size = 4096
  
[ui]
  disable = true
  
[rpc]
  disable = false
  port = 8545
  interface = "0.0.0.0"
  hosts = ["*"]
  apis = ["web3", "eth", "net","parity","parity_accounts","personal", "traces", "rpc", "secretstore", "parity_pubsub"]